services:
  backend:
    build:
      context: ./backend/legalflow
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - legalflow-net

  frontend:
    build:
      context: ./frontend/legalflow
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - backend
    networks:
      - legalflow-net

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: legalflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - legalflow-net

networks:
  legalflow-net:
    driver: bridge

volumes:
  postgres_data: