name: Legalflow Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"

      - name: Build Backend
        run: mvn clean install -f backend/legalflow/pom.xml

      - name: Test Backend
        run: mvn test -f backend/legalflow/pom.xml

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Frontend Dependencies
        run: npm install --prefix frontend/legalflow

      - name: Build Frontend
        run: npm run build --prefix frontend/legalflow

      - name: Test Frontend
        run: npm run test --prefix frontend/legalflow
