name: Build and Push Frontend Docker Image to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        run: |
          az acr login --name legalflowfrontend

      - name: Build the Docker image
        run: |
          docker build -t legalflowfrontend.azurecr.io/legalflow-frontend:latest ./frontend/legalflow

      - name: Push the Docker image to ACR
        run: |
          docker push legalflowfrontend.azurecr.io/legalflow-frontend:latest

      - name: Clean up Docker images
        run: |
          docker rmi legalflowfrontend.azurecr.io/legalflow-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Create GitHub Deployment
        uses: chrnorm/deployment-action@v2
        id: deployment
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          environment: production
          environment-url: https://www.legalflow.online
