name: Build and Push Backend Docker Image to ACR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        run: |
          az acr login --name legalflowbackend

      - name: Create GitHub Deployment
        id: create_deployment
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/deployments \
          -d '{"ref": "${{ github.sha }}", "environment": "production", "description": "Deploying backend", "required_contexts": []}'

      - name: Build the Docker image
        run: |
          docker build -t legalflowbackend.azurecr.io/legalflow-backend:latest ./backend/legalflow

      - name: Push the Docker image to ACR
        run: |
          docker push legalflowbackend.azurecr.io/legalflow-backend:latest

      - name: Clean up Docker images
        run: |
          docker rmi legalflowbackend.azurecr.io/legalflow-backend:latest

      - name: Update Deployment Status to Success
        if: success()
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/deployments/${{ steps.create_deployment.outputs.id }}/statuses \
          -d '{"state": "success"}'

      - name: Update Deployment Status to Failure
        if: failure()
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/deployments/${{ steps.create_deployment.outputs.id }}/statuses \
          -d '{"state": "failure"}'
